### ISSUE TITLE
Responsive affix

### ISSUE THREAD

**Issue by edmundoa** [react-bootstrap/react-overlays#63]
Hello,

I am trying to create a responsive affix with react-overlays. The idea is to have a sidebar that is shown on the left side of the screen on large displays, but that it displays on top of the screen when on small displays. That sidebar will at the same time use an `AutoAffix` to follow the user's scroll on large displays.

Using plain bootstrap, I could achieve that with some CSS:
```css
@media (max-width: @screen-md-min) {
  #sidebar .affix {
    position: relative;
  }
}
@media (min-width: @screen-md-min) {
  #sidebar .affix {
    top: 45px;
    z-index: 1000;
    position: fixed;
  }
}
```

I could do the same using react-overlays by setting an `affixClassName`, but the in-line styles applied by the `Affix` component override the styling from the CSS. I would really like to avoid having to check the window width and assign in-line styles by hand.

In case I am missing something, have you got any ideas on how to achieve this? If not, would you consider changing the way `Affix` sets the positioning to allow this use case? I could work on the changes myself if necessary.

Here are the component using the sidebar, and the sidebar, in case you want to take a look:
https://github.com/Graylog2/graylog2-server/blob/ecfeee91aa1ba1226c64513f7daff79d1c904198/graylog2-web-interface/src/components/search/SearchResult.jsx#L178
https://github.com/Graylog2/graylog2-server/blob/0af59765252f835bd9753add850fa63fca91083d/graylog2-web-interface/src/components/search/SearchSidebar.jsx#L157

Thank you in advance!
